artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  SRC_URL: https://drive.google.com/file/d/1Tko9HIi34Rsn0Yk59x_nSljKSq_RStU5/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
